version: '3'

services:
  backend:
    build:
      context: ./api
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis-16359.c15.us-east-1-4.ec2.redns.redis-cloud.com 
      - REDIS_PORT=16359
      - REDIS_PASS=PuUQhAAhdm2oKl3aVFFBXjIWuz0WMFKK
    networks:
      - app-network

  frontend:
    build:
      context: ./ui
    ports:
      - "80:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

  # redis:
  #   image: "redis:latest"  
  #   ports:
  #     - "6379:6379" 
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge